"""add_pool_use_count_and_pool_status

Revision ID: 00362b26efcb
Revises: 47a1d8b041a2
Create Date: 2026-04-07 19:34:24.778322

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '00362b26efcb'
down_revision: str | Sequence[str] | None = '47a1d8b041a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('accounts', sa.Column('pool_use_count', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('pool_status', sa.String(), nullable=True))

    # 设置默认值
    op.execute("UPDATE accounts SET pool_use_count = 0 WHERE pool_use_count IS NULL")
    op.execute("UPDATE accounts SET pool_status = '' WHERE pool_status IS NULL")

    # 回填: 已有 family_use_count 数据迁移到 pool_use_count
    op.execute("""
        UPDATE accounts SET pool_use_count = family_use_count
        WHERE family_use_count IS NOT NULL AND family_use_count > 0
    """)

    op.drop_column('accounts', 'family_use_count')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('family_use_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'pool_status')
    op.drop_column('accounts', 'pool_use_count')
    # ### end Alembic commands ###
