"""drop account country columns

Revision ID: 304a18ac2872
Revises: 45b599f17cee
Create Date: 2026-04-11 01:05:03.823629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304a18ac2872'
down_revision: Union[str, Sequence[str], None] = '45b599f17cee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'country_cn')
    op.drop_column('accounts', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('country_cn', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
