"""add_pool_last_used_at

Revision ID: 45b599f17cee
Revises: 00362b26efcb
Create Date: 2026-04-07 21:29:48.936845

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '45b599f17cee'
down_revision: str | Sequence[str] | None = '00362b26efcb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('pool_last_used_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'pool_last_used_at')
    # ### end Alembic commands ###
