"""initial schema — drop legacy columns and invite_results table

Revision ID: 47a1d8b041a2
Revises:
Create Date: 2026-04-04 14:40:12.397834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47a1d8b041a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invite_results')
    op.drop_column('accounts', 'google_has_family')
    op.drop_column('accounts', 'age_verify_url')
    op.drop_column('family_groups', 'age_verify_urls')
    op.drop_column('family_groups', 'tags')
    op.drop_column('family_groups', 'last_replaced_at')
    op.drop_column('sms_providers', 'default_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_providers', sa.Column('default_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('family_groups', sa.Column('last_replaced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('family_groups', sa.Column('tags', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('family_groups', sa.Column('age_verify_urls', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('age_verify_url', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('google_has_family', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('invite_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_email', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('marked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('rpc_status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rpc_raw_response', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('rpc_parsed_response', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('invite_results_account_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invite_results_pkey'))
    )
    # ### end Alembic commands ###
