"""drop account tags column

Revision ID: 785fbf1b23f0
Revises: 304a18ac2872
Create Date: 2026-04-11 01:20:52.225309

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '785fbf1b23f0'
down_revision: str | Sequence[str] | None = '304a18ac2872'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
